name: format C code

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
      - name: Push changes back to repo
        if: ${{ steps.pre-commit.outcome == 'failure' }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "style: auto format code with pre-commit"
          git push
